apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo
  links:
    - url: https://dashboard.example.com
      title: My Dashboard
      icon: dashboard
  description: An example deployment of a Backstage application.
  annotations:
    github.com/project-slug: backstage/demo
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: backstage/maintainers
  lifecycle: experimental