apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: recruiter-selfService
  tags:
    - react
    - nextjs
    - typescript
  links:
    - url: https://github.com/occmundial/recruiter-selfService
      title: Repositorio
      icon: dashboard
  description: Creación de cuenta y primera publicación de vacante.
  annotations:
    github.com/project-slug: backstage/demo
    backstage.io/techdocs-ref: url:https://github.com/occmundial/api-hirers-genesis
spec:
  consumesApis:
    - example-grpc-api
  type: website
  owner: backstage/maintainers
  lifecycle: production